### ISSUE TITLE
error with example_by_radius.py

### ISSUE THREAD

**Issue by jkteske** [CaymanUnterborn/ExoPlex#8]
I get the following error when trying to run this cod, which isn't easy for me to parse, any ideas?

Thanks,

Johanna

 

bash-3.2$ python example_by_radius.py

Core composition:  {'Fe': 100.0, 'Si': 0.0, 'O': 0.0, 'S': 0.0}
Mantle composition:  {'FeO': 0.0, 'SiO2': 52.55497015, 'MgO': 39.17101638, 'CaO': 3.81493827, 'Al2O3': 4.45907521}
Mantle Fe# -0.0
Core Mass Percent =  32.816

Your closest grid filename is:  0.07CaMg_0.00FeMg_0.09AlMg_0.9SiMg_0.0NaMg_0.00Fe_U/LM_results.txt

Core composition:  {'Fe': 100.0, 'Si': 0.0, 'O': 0.0, 'S': 0.0}
Mantle composition:  {'FeO': 0.0, 'SiO2': 52.55497015, 'MgO': 39.17101638, 'CaO': 3.81493827, 'Al2O3': 4.45907521}
Mantle Fe# -0.0
Core Mass Percent =  32.816

The Upper mantle .tab already exists, please wait briefly for solution

The Lower mantle .tab already exists, please wait briefly for solution

Traceback (most recent call last):
  File "example_by_radius.py", line 92, in <module>
    Planet = exo.run_planet_radius(Radius_planet,compositional_params,structure_params,layers,filename)
  File "/Users/jteske/Dropbox/Teaching:Outreach/Kendra/ExoPlex/ExoPlex/ExoPlex/run_planet.py", line 60, in run_planet_radius
    Planet = functions.find_Planet_radius(radius_planet, core_mass_frac,structure_params, compositional_params, grids, Core_wt_per, layers)
  File "/Users/jteske/Dropbox/Teaching:Outreach/Kendra/ExoPlex/ExoPlex/ExoPlex/functions.py", line 801, in find_Planet_radius
    structure_params[6] = brentq(calc_CRF,0.25,0.65,args=args,xtol=1e-4)
  File "/Users/jteske/anaconda/envs/wobble/lib/python3.7/site-packages/scipy/optimize/zeros.py", line 754, in brentq
    r = _zeros._brentq(f, a, b, xtol, rtol, maxiter, args, full_output, disp)
  File "/Users/jteske/Dropbox/Teaching:Outreach/Kendra/ExoPlex/ExoPlex/ExoPlex/functions.py", line 726, in calc_CRF
    Planet = planet.compress_radius(*[Planet, grids, Core_wt_per, structure_params, layers])
  File "/Users/jteske/Dropbox/Teaching:Outreach/Kendra/ExoPlex/ExoPlex/ExoPlex/planet.py", line 311, in compress_radius
    Planet['gravity'] = minphys.get_gravity(Planet,layers)
  File "/Users/jteske/Dropbox/Teaching:Outreach/Kendra/ExoPlex/ExoPlex/ExoPlex/minphys.py", line 490, in get_gravity
    rhofunc_core = interpolate.UnivariateSpline(radii_core, density_core)
  File "/Users/jteske/anaconda/envs/wobble/lib/python3.7/site-packages/scipy/interpolate/fitpack2.py", line 177, in __init__
    raise ValueError('x must be strictly increasing')
ValueError: x must be strictly increasing

**Comment by CaymanUnterborn** [comment]
Thanks for pointing this out Johanna! Didn't see any email about this so I'm just seeing this error now. The latest version of the code should take care of this as this bit of code has been optimized.
